Renaming Visualizer.cpp to Visualizer.cu, so that it gets handled by CUDA compiler and resolve the following link error:
/usr/bin/ld: CMakeFiles/surfremesh.dir/src/gDel2D/gDel2D/GPU/GpuDelaunay.cu.o: in function `GpuDel::doInsertConstraints()':
tmpxft_000003c2_00000000-6_GpuDelaunay.cudafe1.cpp:(.text+0x34dc): undefined reference to `Visualizer::addFrame(DevVector<Point2> const&, DevVector<Segment> const&, DevVector<Tri> const&, thrust::THRUST_200500_800_NS::host_vector<int, std::allocator<int> > const&, int)'
/usr/bin/ld: tmpxft_000003c2_00000000-6_GpuDelaunay.cudafe1.cpp:(.text+0x363c): undefined reference to `Visualizer::addFrame(DevVector<Point2> const&, DevVector<Segment> const&, DevVector<Tri> const&, thrust::THRUST_200500_800_NS::host_vector<int, std::allocator<int> > const&, int)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/surfremesh.dir/build.make:334: surfremesh] Error 1

This symbol is requested:

$ nm -C CMakeFiles/surfremesh.dir/src/gDel2D/gDel2D/GPU/GpuDelaunay.cu.o | grep addFrame
                 U Visualizer::addFrame(DevVector<Point2> const&, DevVector<Segment> const&, DevVector<Tri> const&, thrust::THRUST_200500_800_NS::host_vector<int, std::allocator<int> > const&, int)

However, only this symbol is present:

$ nm -C CMakeFiles/surfremesh.dir/src/gDel2D/Visualizer.cpp.o | grep addFrame
0000000000003724 T Visualizer::addFrame(DevVector<Point2> const&, DevVector<Tri> const&, int)
0000000000003a06 T Visualizer::addFrame(DevVector<Point2> const&, DevVector<Segment> const&, DevVector<Tri> const&, thrust::THRUST_200500___CUDA_ARCH_LIST___NS::host_vector<int, std::allocator<int> > const&, int)

Note there is "__CUDA_ARCH_LIST__" instead of "800" in the name, because "__CUDA_ARCH_LIST__" in CMake this macro is only substituted by the CUDA compiler. Therefore, the easiest fix is to use CUDA compiler for Visualizer.cpp